### ISSUE TITLE
Run an updated build to include a recent bugfix

### ISSUE THREAD

**Issue by heatherhosler** [Plattar/python-usd#9]
I am having a problem with [this bug](https://github.com/PixarAnimationStudios/OpenUSD/issues/1902).
It has been fixed in a recent version of OpenUSD.
However, this repo's most recent build was last year.

Any chance of triggering another build using OpenUSD v23.11, which is the latest?

As this is upstream, I'm guessing it's going to be required for [the issue](https://github.com/Plattar/python-usd-ar/issues/7) I reported on the other project `python-usd-ar`.

Many thanks, while waiting, I will clone & try to figure out how to get it working, although I've not used GitHub workflows before so I don't exactly know what I'm doing.

**Comment by DavidArayan** [comment]
A prebuilt version that uses OpenUSD v23.11 is now available on Dockerhub. See the linked PR. I will initiate a build of the [python-usd-ar Issue 7](https://github.com/Plattar/python-usd-ar/issues/7) that uses this new image. The build takes several hours so ~24 hours will be available.
